# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('type', models.IntegerField(choices=[(1, 'Alimentação')], max_length=1)),
            ],
        ),
    ]
