# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.IntegerField(choices=[(1, 'Alimentação')]),
        ),
    ]
