# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20170305_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.IntegerField(choices=[(1, 'Alimentação'), (2, 'Como estou me sentido?')]),
        ),
    ]
