# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import src.reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20170305_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Good'), (1, 'Bad')], default=0)),
                ('score', models.IntegerField(validators=[src.reports.models.validate_range])),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 31, 18, 17, 51, 273977, tzinfo=utc), verbose_name='Criado'),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.IntegerField(choices=[(0, 'Alimentação'), (1, 'Como estou me sentido?')], default=1),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='reports.Report'),
        ),
    ]
