test-warnings: false
strictness: veryhigh
max-line-length: 120
uses:
  - django
autodetect: true
requirements:
  - requirements.txt
ignore-paths:
  - docs
  - contrib
  - deploy_utils
ignore-patterns:
  - (^|/)docs(/|$)
python-targets:
  - 3